name: Artfact Downloads
on: push

jobs:
  any-old-job-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Make the File
        run: |
          touch my_file_to_download
          echo "Some stuff" >> my_file_to_download
          echo "More stuff" >> my_file_to_download
      - name: Download File to Artfacts
        uses: actions/upload-artifact@v4
        with:
          name: my_file_to_download
          path: /home/runner/work/github_actions_demo_2025/github_actions_demo_2025/my_file_to_download
