name: GitHub Custom Actions
on: workflow_dispatch

jobs:
  checkout-git-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Investigate Repo
        run: |
          pwd
          ls -lart
          cd ./github_actions_demo_2025
          ls -lart
